### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by bvnn** [inocan-group/vue3-google-map#16] opened 2021-01-29 15:35 UTC
Hello,
I am new in VueJs and I would like to ask that I can use the search box for the maps?
And if yes, how can I use it? 
Thanks

**Comment by HusamIbrahim** [comment] 2021-02-01 08:51
Hey @bvnn,

If you're referring to the places autocomplete API then unfortunately we don't have a component that implements it currently.

**Comment by bvnn** [comment] 2021-02-01 15:00
And How can I use the API?
I checked that: https://vue3-google-map.netlify.app/advanced-usage/
But I can't access the api.

**Comment by HusamIbrahim** [comment] 2021-02-01 20:49
Can you share an example or a reproduction link?

**Comment by baradhili** [comment] 2021-04-13 03:42
@HusamIbrahim could this be marked as a feature request?

**Comment by HusamIbrahim** [comment] 2021-04-15 21:10
@baradhili we have a backlog of bugs we need to work through first. I also think it might be better for search functionality to be implemented on the user side for better control of look and feel. Happy to be convinced otherwise though.

**Comment by ksnyde** [comment] 2021-04-22 01:27
@bvnn Sorry i'm reading this and not understanding what the issue is. What is it in the API that you can't access? What is the search functionality you are referring to? Can you provide a link to Google where this is documented?

**Comment by VitAndrGuid** [comment] 2021-04-26 16:00
I think what he wants can be easily achieved with a custom control plus a input and his own integration with the places or routing api

**Comment by ksnyde** [comment] 2021-04-26 16:33
@baradhili based on the suggested work-around I am going to close this issue but if you feel it should be solved a different way and want to provide a PR for this we are happy to review that.

**Closed by ksnyde** 2021-04-26 16:33 UTC
