### ISSUE TITLE
google.maps.Marker in the Maps JavaScript API (Deprecated as of February 2023)

### ISSUE THREAD

**Issue by melt-snow** [inocan-group/vue3-google-map#200] opened 2024-02-24 07:31 UTC
According to https://developers.google.com/maps/deprecations?hl=en, google.maps.Marker will be discontinued.
Google recommends using google.maps.marker.AdvancedMarkerElement.

any plans to do so?

**Comment by rdy3e24r2d2** [comment] 2024-02-26 09:50
I have the same question.

**Comment by HusamIbrahim** [comment] 2024-02-26 18:32
Closing this one as it's a duplicate of #199

**Closed by HusamIbrahim** 2024-02-26 18:32 UTC
Labels: duplicate
